version: "3"

volumes:
  local_mysql_data: {}

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: netflix
    volumes:
      - local_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
